-- 1. Update PRODUCTS table for Margin & Competitor Intel
alter table products 
add column if not exists cost_price numeric default 0,
add column if not exists competitor_url text,
add column if not exists competitor_price numeric,
add column if not exists auto_pricing_enabled boolean default false;

-- 2. Create SEARCH_LOGS table for Trend Oracle
create table if not exists search_logs (
  id bigint primary key generated always as identity,
  query text not null,
  user_id uuid references auth.users,
  results_count integer default 0,
  created_at timestamptz default now()
);

-- 3. Create COUPONS table for Negotiator
-- (Assuming table didn't exist, creating fresh. If exists, we'd alter)
create table if not exists coupons (
  id bigint primary key generated always as identity,
  code text unique not null,
  discount_percent numeric not null,
  is_hidden boolean default false, -- True if generated by AI for a specific user
  generated_for_user uuid references auth.users, -- Locked to user
  valid_until timestamptz,
  created_at timestamptz default now()
);

-- 4. Create BLACKLISTS table for Fraud Predator
create table if not exists blacklists (
  id bigint primary key generated always as identity,
  user_id uuid references auth.users,
  ip_address text,
  reason text,
  shadow_banned boolean default true,
  created_at timestamptz default now()
);

-- RLS Policies (Security)
alter table search_logs enable row level security;
alter table coupons enable row level security;
alter table blacklists enable row level security;

-- Search Logs: Anyone can insert, only admins read (simplified for demo)
create policy "Enable insert for everyone" on search_logs for insert with check (true);

-- Coupons: Public read (or limited), Admin write
create policy "Read coupons" on coupons for select using (true);

-- Blacklists: Admin only
-- (For demo purposes allowing read/write to authenticated for simplicity, enforcing in logic)
create policy "Admin access blacklist" on blacklists for all using (auth.role() = 'authenticated');
